export const fleet = [
  {
    id: 'lancer',
    showroomScene: '/images/lancer-reference-showroom.webp',
    showroomCutout: '/images/lancer-reference-cutout.webp',
    showroomMask: '/images/lancer-reference-alpha.png',
    cutout: '/images/lancer-reference-cutout.png',
    category: 'Económico',
    make: 'Mitsubishi',
    model: 'Lancer',
    watermark: 'LANCER',
    price: 75,
    passengers: 5,
    bags: 2,
    doors: 4,
    image: '/images/lancer-reference-scene.webp',
    mobileImage: '/images/lancer-reference-mobile.webp',
    thumbnail: '/images/lancer-reference-thumb.webp',
    description:
      'Para moverte a tu ritmo. Práctico, cómodo y listo para la ciudad.',
  },
  {
    id: 'cruze',
    showroomScene: '/images/showroom-cruze.webp',
    showroomCutout: '/images/showroom-cruze-cutout.webp',
    showroomMask: '/images/showroom-cruze-mask.webp',
    cutout: '/images/cruze.png',
    category: 'Premium',
    make: 'Chevrolet',
    model: 'Cruze',
    watermark: 'CRUZE',
    price: 85,
    passengers: 5,
    bags: 2,
    doors: 4,
    image: '/images/cruze-scene.webp',
    mobileImage: '/images/cruze-mobile.webp',
    thumbnail: '/images/cruze-thumb.webp',
    description:
      'Haz espacio para disfrutar. Comodidad para tus días en Maracaibo.',
  },
  {
    id: 'camry',
    showroomScene: '/images/showroom-camry.webp',
    showroomCutout: '/images/showroom-camry-cutout.webp',
    showroomMask: '/images/showroom-camry-mask.webp',
    cutout: '/images/camry.png',
    category: 'Luxury',
    make: 'Toyota',
    model: 'Camry',
    watermark: 'CAMRY',
    price: 110,
    passengers: 5,
    bags: 3,
    doors: 4,
    image: '/images/camry-scene.webp',
    mobileImage: '/images/camry-mobile.webp',
    thumbnail: '/images/camry-thumb.webp',
    description: 'Un poco más de espacio. Un viaje cómodo, de principio a fin.',
  },
  {
    id: 'cherokee',
    showroomScene: '/images/showroom-cherokee.webp',
    showroomCutout: '/images/showroom-cherokee-cutout.webp',
    showroomMask: '/images/showroom-cherokee-mask.webp',
    cutout: '/images/cherokee.png',
    category: 'SUV',
    make: 'Jeep',
    model: 'Cherokee',
    watermark: 'CHEROKEE',
    price: 130,
    passengers: 5,
    bags: 3,
    doors: 4,
    image: '/images/cherokee-scene.webp',
    mobileImage: '/images/cherokee-mobile.webp',
    thumbnail: '/images/cherokee-thumb.webp',
    description:
      'Para los planes que piden más. Tú decides hasta dónde llegar.',
  },
  {
    id: 'explorer',
    showroomScene: '/images/showroom-explorer.webp',
    showroomCutout: '/images/showroom-explorer-cutout.webp',
    showroomMask: '/images/showroom-explorer-mask.webp',
    cutout: '/images/explorer.png',
    category: 'SUV Luxury',
    make: 'Ford',
    model: 'Explorer',
    watermark: 'EXPLORER',
    price: 160,
    passengers: 7,
    bags: 4,
    doors: 4,
    image: '/images/explorer-scene.webp',
    mobileImage: '/images/explorer-mobile.webp',
    thumbnail: '/images/explorer-thumb.webp',
    description:
      'Que no se quede nadie. Siete puestos para compartir el camino.',
  },
] as const;
export type Vehicle = (typeof fleet)[number];
